SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define :thzeribiS do |server|
		server.vm.hostname = 'thzeribiS'
		server.vm.network "private_network", ip: SERVER_IP
		server.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribiS"]
		end
		server.vm.provision "file", source: "manifests", destination: "/tmp/"
		server.vm.provision "shell", privileged: true, path: "scripts/server.sh", args:["/tmp/manifests/", SERVER_IP]
	end
end
