Vagrant.configure("2") do |config|
	config.vm.box = "boxomatic/debian-12"
	
	config.ssh.username = 'root'
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true
	config.ssh.insert_key = true
	config.ssh.config = ".ssh/config"
	config.ssh.private_key_path = ".ssh/id_rsa"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define :thzeribiS do |server|
		server.vm.hostname = 'thzeribiS'
		server.vm.network "private_network", ip: '192.168.56.110'
		server.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribiS"]
		end
		# server.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
		# server.vm.provision "file", source: ".ssh/id_rsa", destination: "~/.ssh/id_rsa"
	end

	config.vm.define :thzeribiSW do |worker|
		worker.vm.hostname = 'thzeribiSW'
		worker.vm.network "private_network", ip: '192.168.56.111'
		worker.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribiSW"]
		end
	# 	worker.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
	# 	worker.vm.provision "file", source: ".ssh/id_rsa", destination: "~/.ssh/id_rsa"
	end
end
