SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true
	config.ssh.config = ".ssh/config"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define :thzeribiS do |server|
		server.vm.hostname = 'thzeribiS'
		server.vm.network "private_network", ip: SERVER_IP
		server.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribiS"]
		end
		server.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "/tmp/.ssh/id_rsa.pub"
		server.vm.provision "file", source: ".ssh/id_rsa", destination: "/tmp/.ssh/id_rsa"
		server.vm.provision "shell", privileged: true, path: "scripts/server.sh", args:["/tmp/.ssh/", SERVER_IP]
	end

	config.vm.define :thzeribiSW do |worker|
		worker.vm.hostname = 'thzeribiSW'
		worker.vm.network "private_network", ip: WORKER_IP
		worker.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribiSW"]
		end
		worker.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "/tmp/.ssh/id_rsa.pub"
		worker.vm.provision "file", source: ".ssh/id_rsa", destination: "/tmp/.ssh/id_rsa"
		worker.vm.provision "shell", privileged: true, path: "scripts/worker.sh", args:["/tmp/.ssh/", WORKER_IP, SERVER_IP, "thzeribiS"]
	end
end
