Vagrant.configure("2") do |config|
	config.vm.box = "generic/debian12"
	
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	config.vm.define :thzeribiS do |server|
		server.vm.hostname = 'thzeribi'
		server.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--name", "thzeribi"]
		end

		server.vm.provision "shell", privileged: true, path: "scripts/enable_X11.sh"
		server.vm.provision "file", source: "scripts/install.sh", destination: "$HOME/scripts/"

	end
end
